name: grindly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  get_it: ^8.0.3
  bloc: ^9.0.0
  meta: ^1.16.0
  flutter_bloc: ^9.1.1
  go_router: ^16.0.0
  equatable: ^2.0.7
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google.png
    - assets/lottie_animations/email-verification.json
  fonts:
    - family: 'JacquesFrancois'
      fonts:
        - asset: assets/fonts/Jacques_Francois/JacquesFrancois-Regular.ttf
